# based on nginx
FROM sinet/nginx-node:5.9.1

# autor
MAINTAINER FBROER_JAPPELFELLER

# install necessary packages
USER root
RUN apt-get -y update
RUN apt-get --force-yes -y install nginx
RUN apt-get --force-yes -y install git

RUN npm install simple-peer --save  # add WebRTC 

# nginx config 
COPY default.conf /etc/nginx/conf.d/default.conf

# get data
WORKDIR home
RUN git clone https://fb970419:password@git.fh-muenster.de/ja753563/WebRTCDemonstrator.git
WORKDIR WebRTCDemonstrator
RUN git checkout 5-layout-implementieren

# copy data
RUN cp -r website/src/html/* /usr/share/nginx/html
RUN cp -r website/src/* /usr/share/nginx/html


